#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# install theme's deps
cd /app/theme && npm install

python /app/manage.py tailwind build
python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
